$(document).ready(function(){
    $('.food-slider').slick({
        autoplay:true,
     slideToShow:3,
     slidesToScroll:1,
     prevArrow:".prev-btn",
     nextArrow:".next-btn"
    });
});